baseURL = "https://ekeough6.github.io/"
languageCode = "en-us"
title = "Eric Keough"
theme = "hugo-lamp"
enableRobotsTXT = true
PygmentCodeFences = true
canonifyurls = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Projects"
  weight = 30
  identifier = "projects"
  url = "/projects/"

[[menu.main]]
  name = "Academics"
  weight = 40
  identifier = "academics"
  url = "/academics/"

[params]
  author = "Eric Keough"
  logo = "/img/clown.jpg"
  seotitle = "A page about me"
  subtitle = "A simple computer science student"
  description = "A website made by a simple college student"
  paginate = 10

  # Choose your social networks
  email = "erickeough6@gmail.com"
  github = "ekeough6"
  linkedin = "eric-keough/"
